apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: '{{ .Values.werf.image.portfolio }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: 'portfolio'
            - name: EKP_PLUGIN_NAME
              value: 'Portfolio'
            - name: MORALIS_APP_ID
              value: '{{ .Values.moralis.appId }}'
            - name: MORALIS_SERVER_URL
              value: '{{ .Values.moralis.serverUrl }}'
            - name: MONGO_HOST
              value: '{{ .Values.mongodb.host }}'
            - name: REDIS_HOST
              value: 'ekp-portfolio-redis-master'
            - name: OPENSEA_API_KEY
              value: '{{ .Values.opensea.apiKey }}'
          ports:
            - containerPort: 3001
              protocol: TCP
